SELECT DISTINCT(CITY)
FROM STATION
WHERE SUBSTR(CITY, 0, 1) NOT IN ('A','E','I','O','U');

SELECT DISTINCT(CITY)
FROM STATION
WHERE LOWER(SUBSTR(CITY, 0, 1)) NOT IN ('a,'e','i','o','u');

SELECT DISTINCT CITY FROM STATION
WHERE CITY REGEXP '^[^aeiou]';

